export const browserCoreExamples = [
  "tigerpaw browser status",
  "tigerpaw browser start",
  "tigerpaw browser stop",
  "tigerpaw browser tabs",
  "tigerpaw browser open https://example.com",
  "tigerpaw browser focus abcd1234",
  "tigerpaw browser close abcd1234",
  "tigerpaw browser screenshot",
  "tigerpaw browser screenshot --full-page",
  "tigerpaw browser screenshot --ref 12",
  "tigerpaw browser snapshot",
  "tigerpaw browser snapshot --format aria --limit 200",
  "tigerpaw browser snapshot --efficient",
  "tigerpaw browser snapshot --labels",
];

export const browserActionExamples = [
  "tigerpaw browser navigate https://example.com",
  "tigerpaw browser resize 1280 720",
  "tigerpaw browser click 12 --double",
  'tigerpaw browser type 23 "hello" --submit',
  "tigerpaw browser press Enter",
  "tigerpaw browser hover 44",
  "tigerpaw browser drag 10 11",
  "tigerpaw browser select 9 OptionA OptionB",
  "tigerpaw browser upload /tmp/openclaw/uploads/file.pdf",
  'tigerpaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "tigerpaw browser dialog --accept",
  'tigerpaw browser wait --text "Done"',
  "tigerpaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "tigerpaw browser console --level error",
  "tigerpaw browser pdf",
];
